//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace DataHubServicesAddin.LocatorHub {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="LocatorHubSoap", Namespace="http://www.esriuk.com/locatorhub")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PickItem[]))]
    public partial class LocatorHub : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RectifyOperationCompleted;
        
        private System.Threading.SendOrPostCallback Rectify_BinaryOperationCompleted;
        
        private System.Threading.SendOrPostCallback GeocodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback Geocode_BinaryOperationCompleted;
        
        private System.Threading.SendOrPostCallback MatchOperationCompleted;
        
        private System.Threading.SendOrPostCallback Match_BinaryOperationCompleted;
        
        private System.Threading.SendOrPostCallback FetchRecordOperationCompleted;
        
        private System.Threading.SendOrPostCallback FetchRecord_BinaryOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReverseGeocodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReverseGeocode_BinaryOperationCompleted;
        
        private System.Threading.SendOrPostCallback CapabilitiesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListLocatorsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public LocatorHub() {
            this.Url = global::DataHubServicesAddin.Properties.Settings.Default.DataHubServicesAddin_LocatorHub_LocatorHub;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RectifyCompletedEventHandler RectifyCompleted;
        
        /// <remarks/>
        public event Rectify_BinaryCompletedEventHandler Rectify_BinaryCompleted;
        
        /// <remarks/>
        public event GeocodeCompletedEventHandler GeocodeCompleted;
        
        /// <remarks/>
        public event Geocode_BinaryCompletedEventHandler Geocode_BinaryCompleted;
        
        /// <remarks/>
        public event MatchCompletedEventHandler MatchCompleted;
        
        /// <remarks/>
        public event Match_BinaryCompletedEventHandler Match_BinaryCompleted;
        
        /// <remarks/>
        public event FetchRecordCompletedEventHandler FetchRecordCompleted;
        
        /// <remarks/>
        public event FetchRecord_BinaryCompletedEventHandler FetchRecord_BinaryCompleted;
        
        /// <remarks/>
        public event ReverseGeocodeCompletedEventHandler ReverseGeocodeCompleted;
        
        /// <remarks/>
        public event ReverseGeocode_BinaryCompletedEventHandler ReverseGeocode_BinaryCompleted;
        
        /// <remarks/>
        public event CapabilitiesCompletedEventHandler CapabilitiesCompleted;
        
        /// <remarks/>
        public event ListLocatorsCompletedEventHandler ListLocatorsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.esriuk.com/locatorhub/Rectify", RequestNamespace="http://www.esriuk.com/locatorhub", ResponseNamespace="http://www.esriuk.com/locatorhub", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RectifyResult Rectify(string LocatorName, string Matcher, string Query, bool inFuzzy, int inReturnCoordinateSystem) {
            object[] results = this.Invoke("Rectify", new object[] {
                        LocatorName,
                        Matcher,
                        Query,
                        inFuzzy,
                        inReturnCoordinateSystem});
            return ((RectifyResult)(results[0]));
        }
        
        /// <remarks/>
        public void RectifyAsync(string LocatorName, string Matcher, string Query, bool inFuzzy, int inReturnCoordinateSystem) {
            this.RectifyAsync(LocatorName, Matcher, Query, inFuzzy, inReturnCoordinateSystem, null);
        }
        
        /// <remarks/>
        public void RectifyAsync(string LocatorName, string Matcher, string Query, bool inFuzzy, int inReturnCoordinateSystem, object userState) {
            if ((this.RectifyOperationCompleted == null)) {
                this.RectifyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRectifyOperationCompleted);
            }
            this.InvokeAsync("Rectify", new object[] {
                        LocatorName,
                        Matcher,
                        Query,
                        inFuzzy,
                        inReturnCoordinateSystem}, this.RectifyOperationCompleted, userState);
        }
        
        private void OnRectifyOperationCompleted(object arg) {
            if ((this.RectifyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RectifyCompleted(this, new RectifyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.esriuk.com/locatorhub/Rectify_Binary", RequestNamespace="http://www.esriuk.com/locatorhub", ResponseNamespace="http://www.esriuk.com/locatorhub", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Rectify_Binary(string LocatorName, string Matcher, string Query, bool inFuzzy, int inReturnCoordinateSystem) {
            object[] results = this.Invoke("Rectify_Binary", new object[] {
                        LocatorName,
                        Matcher,
                        Query,
                        inFuzzy,
                        inReturnCoordinateSystem});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void Rectify_BinaryAsync(string LocatorName, string Matcher, string Query, bool inFuzzy, int inReturnCoordinateSystem) {
            this.Rectify_BinaryAsync(LocatorName, Matcher, Query, inFuzzy, inReturnCoordinateSystem, null);
        }
        
        /// <remarks/>
        public void Rectify_BinaryAsync(string LocatorName, string Matcher, string Query, bool inFuzzy, int inReturnCoordinateSystem, object userState) {
            if ((this.Rectify_BinaryOperationCompleted == null)) {
                this.Rectify_BinaryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRectify_BinaryOperationCompleted);
            }
            this.InvokeAsync("Rectify_Binary", new object[] {
                        LocatorName,
                        Matcher,
                        Query,
                        inFuzzy,
                        inReturnCoordinateSystem}, this.Rectify_BinaryOperationCompleted, userState);
        }
        
        private void OnRectify_BinaryOperationCompleted(object arg) {
            if ((this.Rectify_BinaryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Rectify_BinaryCompleted(this, new Rectify_BinaryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.esriuk.com/locatorhub/Geocode", RequestNamespace="http://www.esriuk.com/locatorhub", ResponseNamespace="http://www.esriuk.com/locatorhub", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public GeocodeResult Geocode(string LocatorId, string inMatchTerm, string inQuery, bool inUseFuzzySearch, int inReturnCoordinateSystem) {
            object[] results = this.Invoke("Geocode", new object[] {
                        LocatorId,
                        inMatchTerm,
                        inQuery,
                        inUseFuzzySearch,
                        inReturnCoordinateSystem});
            return ((GeocodeResult)(results[0]));
        }
        
        /// <remarks/>
        public void GeocodeAsync(string LocatorId, string inMatchTerm, string inQuery, bool inUseFuzzySearch, int inReturnCoordinateSystem) {
            this.GeocodeAsync(LocatorId, inMatchTerm, inQuery, inUseFuzzySearch, inReturnCoordinateSystem, null);
        }
        
        /// <remarks/>
        public void GeocodeAsync(string LocatorId, string inMatchTerm, string inQuery, bool inUseFuzzySearch, int inReturnCoordinateSystem, object userState) {
            if ((this.GeocodeOperationCompleted == null)) {
                this.GeocodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGeocodeOperationCompleted);
            }
            this.InvokeAsync("Geocode", new object[] {
                        LocatorId,
                        inMatchTerm,
                        inQuery,
                        inUseFuzzySearch,
                        inReturnCoordinateSystem}, this.GeocodeOperationCompleted, userState);
        }
        
        private void OnGeocodeOperationCompleted(object arg) {
            if ((this.GeocodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GeocodeCompleted(this, new GeocodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.esriuk.com/locatorhub/Geocode_Binary", RequestNamespace="http://www.esriuk.com/locatorhub", ResponseNamespace="http://www.esriuk.com/locatorhub", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Geocode_Binary(string LocatorId, string inMatchTerm, string inQuery, bool inUseFuzzySearch, int inReturnCoordinateSystem) {
            object[] results = this.Invoke("Geocode_Binary", new object[] {
                        LocatorId,
                        inMatchTerm,
                        inQuery,
                        inUseFuzzySearch,
                        inReturnCoordinateSystem});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void Geocode_BinaryAsync(string LocatorId, string inMatchTerm, string inQuery, bool inUseFuzzySearch, int inReturnCoordinateSystem) {
            this.Geocode_BinaryAsync(LocatorId, inMatchTerm, inQuery, inUseFuzzySearch, inReturnCoordinateSystem, null);
        }
        
        /// <remarks/>
        public void Geocode_BinaryAsync(string LocatorId, string inMatchTerm, string inQuery, bool inUseFuzzySearch, int inReturnCoordinateSystem, object userState) {
            if ((this.Geocode_BinaryOperationCompleted == null)) {
                this.Geocode_BinaryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGeocode_BinaryOperationCompleted);
            }
            this.InvokeAsync("Geocode_Binary", new object[] {
                        LocatorId,
                        inMatchTerm,
                        inQuery,
                        inUseFuzzySearch,
                        inReturnCoordinateSystem}, this.Geocode_BinaryOperationCompleted, userState);
        }
        
        private void OnGeocode_BinaryOperationCompleted(object arg) {
            if ((this.Geocode_BinaryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Geocode_BinaryCompleted(this, new Geocode_BinaryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.esriuk.com/locatorhub/Match", RequestNamespace="http://www.esriuk.com/locatorhub", ResponseNamespace="http://www.esriuk.com/locatorhub", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MatchResult Match(string LocatorName, string Matcher, string Query, bool inFuzzy, string inPickedItem, int inReturnCoordinateSystem, string inCacheID) {
            object[] results = this.Invoke("Match", new object[] {
                        LocatorName,
                        Matcher,
                        Query,
                        inFuzzy,
                        inPickedItem,
                        inReturnCoordinateSystem,
                        inCacheID});
            return ((MatchResult)(results[0]));
        }
        
        /// <remarks/>
        public void MatchAsync(string LocatorName, string Matcher, string Query, bool inFuzzy, string inPickedItem, int inReturnCoordinateSystem, string inCacheID) {
            this.MatchAsync(LocatorName, Matcher, Query, inFuzzy, inPickedItem, inReturnCoordinateSystem, inCacheID, null);
        }
        
        /// <remarks/>
        public void MatchAsync(string LocatorName, string Matcher, string Query, bool inFuzzy, string inPickedItem, int inReturnCoordinateSystem, string inCacheID, object userState) {
            if ((this.MatchOperationCompleted == null)) {
                this.MatchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMatchOperationCompleted);
            }
            this.InvokeAsync("Match", new object[] {
                        LocatorName,
                        Matcher,
                        Query,
                        inFuzzy,
                        inPickedItem,
                        inReturnCoordinateSystem,
                        inCacheID}, this.MatchOperationCompleted, userState);
        }
        
        private void OnMatchOperationCompleted(object arg) {
            if ((this.MatchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MatchCompleted(this, new MatchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.esriuk.com/locatorhub/Match_Binary", RequestNamespace="http://www.esriuk.com/locatorhub", ResponseNamespace="http://www.esriuk.com/locatorhub", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Match_Binary(string LocatorName, string Matcher, string Query, bool inFuzzy, string inPickedItem, int inReturnCoordinateSystem, string inCacheID) {
            object[] results = this.Invoke("Match_Binary", new object[] {
                        LocatorName,
                        Matcher,
                        Query,
                        inFuzzy,
                        inPickedItem,
                        inReturnCoordinateSystem,
                        inCacheID});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void Match_BinaryAsync(string LocatorName, string Matcher, string Query, bool inFuzzy, string inPickedItem, int inReturnCoordinateSystem, string inCacheID) {
            this.Match_BinaryAsync(LocatorName, Matcher, Query, inFuzzy, inPickedItem, inReturnCoordinateSystem, inCacheID, null);
        }
        
        /// <remarks/>
        public void Match_BinaryAsync(string LocatorName, string Matcher, string Query, bool inFuzzy, string inPickedItem, int inReturnCoordinateSystem, string inCacheID, object userState) {
            if ((this.Match_BinaryOperationCompleted == null)) {
                this.Match_BinaryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMatch_BinaryOperationCompleted);
            }
            this.InvokeAsync("Match_Binary", new object[] {
                        LocatorName,
                        Matcher,
                        Query,
                        inFuzzy,
                        inPickedItem,
                        inReturnCoordinateSystem,
                        inCacheID}, this.Match_BinaryOperationCompleted, userState);
        }
        
        private void OnMatch_BinaryOperationCompleted(object arg) {
            if ((this.Match_BinaryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Match_BinaryCompleted(this, new Match_BinaryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.esriuk.com/locatorhub/FetchRecord", RequestNamespace="http://www.esriuk.com/locatorhub", ResponseNamespace="http://www.esriuk.com/locatorhub", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FetchRecordResult FetchRecord(string inLocatorId, string inMatchTerm, string inRecordId, RecordIdentifierType inRecordIdType, int inReturnCoordinateSystem) {
            object[] results = this.Invoke("FetchRecord", new object[] {
                        inLocatorId,
                        inMatchTerm,
                        inRecordId,
                        inRecordIdType,
                        inReturnCoordinateSystem});
            return ((FetchRecordResult)(results[0]));
        }
        
        /// <remarks/>
        public void FetchRecordAsync(string inLocatorId, string inMatchTerm, string inRecordId, RecordIdentifierType inRecordIdType, int inReturnCoordinateSystem) {
            this.FetchRecordAsync(inLocatorId, inMatchTerm, inRecordId, inRecordIdType, inReturnCoordinateSystem, null);
        }
        
        /// <remarks/>
        public void FetchRecordAsync(string inLocatorId, string inMatchTerm, string inRecordId, RecordIdentifierType inRecordIdType, int inReturnCoordinateSystem, object userState) {
            if ((this.FetchRecordOperationCompleted == null)) {
                this.FetchRecordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFetchRecordOperationCompleted);
            }
            this.InvokeAsync("FetchRecord", new object[] {
                        inLocatorId,
                        inMatchTerm,
                        inRecordId,
                        inRecordIdType,
                        inReturnCoordinateSystem}, this.FetchRecordOperationCompleted, userState);
        }
        
        private void OnFetchRecordOperationCompleted(object arg) {
            if ((this.FetchRecordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FetchRecordCompleted(this, new FetchRecordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.esriuk.com/locatorhub/FetchRecord_Binary", RequestNamespace="http://www.esriuk.com/locatorhub", ResponseNamespace="http://www.esriuk.com/locatorhub", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] FetchRecord_Binary(string inLocatorId, string inMatchTerm, string inRecordId, RecordIdentifierType inRecordIdType, int inReturnCoordinateSystem) {
            object[] results = this.Invoke("FetchRecord_Binary", new object[] {
                        inLocatorId,
                        inMatchTerm,
                        inRecordId,
                        inRecordIdType,
                        inReturnCoordinateSystem});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void FetchRecord_BinaryAsync(string inLocatorId, string inMatchTerm, string inRecordId, RecordIdentifierType inRecordIdType, int inReturnCoordinateSystem) {
            this.FetchRecord_BinaryAsync(inLocatorId, inMatchTerm, inRecordId, inRecordIdType, inReturnCoordinateSystem, null);
        }
        
        /// <remarks/>
        public void FetchRecord_BinaryAsync(string inLocatorId, string inMatchTerm, string inRecordId, RecordIdentifierType inRecordIdType, int inReturnCoordinateSystem, object userState) {
            if ((this.FetchRecord_BinaryOperationCompleted == null)) {
                this.FetchRecord_BinaryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFetchRecord_BinaryOperationCompleted);
            }
            this.InvokeAsync("FetchRecord_Binary", new object[] {
                        inLocatorId,
                        inMatchTerm,
                        inRecordId,
                        inRecordIdType,
                        inReturnCoordinateSystem}, this.FetchRecord_BinaryOperationCompleted, userState);
        }
        
        private void OnFetchRecord_BinaryOperationCompleted(object arg) {
            if ((this.FetchRecord_BinaryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FetchRecord_BinaryCompleted(this, new FetchRecord_BinaryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.esriuk.com/locatorhub/ReverseGeocode", RequestNamespace="http://www.esriuk.com/locatorhub", ResponseNamespace="http://www.esriuk.com/locatorhub", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ReverseGeocodeResult ReverseGeocode(string inLocatorId, string matchTerm, Point point, int inputCoordinateSystem, double maximumSearchRadius, DistanceUnits distanceUnits, int maximumCount, int returnCoordinateSystem) {
            object[] results = this.Invoke("ReverseGeocode", new object[] {
                        inLocatorId,
                        matchTerm,
                        point,
                        inputCoordinateSystem,
                        maximumSearchRadius,
                        distanceUnits,
                        maximumCount,
                        returnCoordinateSystem});
            return ((ReverseGeocodeResult)(results[0]));
        }
        
        /// <remarks/>
        public void ReverseGeocodeAsync(string inLocatorId, string matchTerm, Point point, int inputCoordinateSystem, double maximumSearchRadius, DistanceUnits distanceUnits, int maximumCount, int returnCoordinateSystem) {
            this.ReverseGeocodeAsync(inLocatorId, matchTerm, point, inputCoordinateSystem, maximumSearchRadius, distanceUnits, maximumCount, returnCoordinateSystem, null);
        }
        
        /// <remarks/>
        public void ReverseGeocodeAsync(string inLocatorId, string matchTerm, Point point, int inputCoordinateSystem, double maximumSearchRadius, DistanceUnits distanceUnits, int maximumCount, int returnCoordinateSystem, object userState) {
            if ((this.ReverseGeocodeOperationCompleted == null)) {
                this.ReverseGeocodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReverseGeocodeOperationCompleted);
            }
            this.InvokeAsync("ReverseGeocode", new object[] {
                        inLocatorId,
                        matchTerm,
                        point,
                        inputCoordinateSystem,
                        maximumSearchRadius,
                        distanceUnits,
                        maximumCount,
                        returnCoordinateSystem}, this.ReverseGeocodeOperationCompleted, userState);
        }
        
        private void OnReverseGeocodeOperationCompleted(object arg) {
            if ((this.ReverseGeocodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReverseGeocodeCompleted(this, new ReverseGeocodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.esriuk.com/locatorhub/ReverseGeocode_Binary", RequestNamespace="http://www.esriuk.com/locatorhub", ResponseNamespace="http://www.esriuk.com/locatorhub", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ReverseGeocode_Binary(string inLocatorId, string matchTerm, Point point, int inputCoordinateSystem, double maximumSearchRadius, DistanceUnits distanceUnits, int maximumCount, int returnCoordinateSystem) {
            object[] results = this.Invoke("ReverseGeocode_Binary", new object[] {
                        inLocatorId,
                        matchTerm,
                        point,
                        inputCoordinateSystem,
                        maximumSearchRadius,
                        distanceUnits,
                        maximumCount,
                        returnCoordinateSystem});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void ReverseGeocode_BinaryAsync(string inLocatorId, string matchTerm, Point point, int inputCoordinateSystem, double maximumSearchRadius, DistanceUnits distanceUnits, int maximumCount, int returnCoordinateSystem) {
            this.ReverseGeocode_BinaryAsync(inLocatorId, matchTerm, point, inputCoordinateSystem, maximumSearchRadius, distanceUnits, maximumCount, returnCoordinateSystem, null);
        }
        
        /// <remarks/>
        public void ReverseGeocode_BinaryAsync(string inLocatorId, string matchTerm, Point point, int inputCoordinateSystem, double maximumSearchRadius, DistanceUnits distanceUnits, int maximumCount, int returnCoordinateSystem, object userState) {
            if ((this.ReverseGeocode_BinaryOperationCompleted == null)) {
                this.ReverseGeocode_BinaryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReverseGeocode_BinaryOperationCompleted);
            }
            this.InvokeAsync("ReverseGeocode_Binary", new object[] {
                        inLocatorId,
                        matchTerm,
                        point,
                        inputCoordinateSystem,
                        maximumSearchRadius,
                        distanceUnits,
                        maximumCount,
                        returnCoordinateSystem}, this.ReverseGeocode_BinaryOperationCompleted, userState);
        }
        
        private void OnReverseGeocode_BinaryOperationCompleted(object arg) {
            if ((this.ReverseGeocode_BinaryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReverseGeocode_BinaryCompleted(this, new ReverseGeocode_BinaryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.esriuk.com/locatorhub/Capabilities", RequestNamespace="http://www.esriuk.com/locatorhub", ResponseNamespace="http://www.esriuk.com/locatorhub", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public LocatorCapabilities Capabilities(string inLocatorId) {
            object[] results = this.Invoke("Capabilities", new object[] {
                        inLocatorId});
            return ((LocatorCapabilities)(results[0]));
        }
        
        /// <remarks/>
        public void CapabilitiesAsync(string inLocatorId) {
            this.CapabilitiesAsync(inLocatorId, null);
        }
        
        /// <remarks/>
        public void CapabilitiesAsync(string inLocatorId, object userState) {
            if ((this.CapabilitiesOperationCompleted == null)) {
                this.CapabilitiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCapabilitiesOperationCompleted);
            }
            this.InvokeAsync("Capabilities", new object[] {
                        inLocatorId}, this.CapabilitiesOperationCompleted, userState);
        }
        
        private void OnCapabilitiesOperationCompleted(object arg) {
            if ((this.CapabilitiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CapabilitiesCompleted(this, new CapabilitiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.esriuk.com/locatorhub/ListLocators", RequestNamespace="http://www.esriuk.com/locatorhub", ResponseNamespace="http://www.esriuk.com/locatorhub", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RemoteLocator[] ListLocators() {
            object[] results = this.Invoke("ListLocators", new object[0]);
            return ((RemoteLocator[])(results[0]));
        }
        
        /// <remarks/>
        public void ListLocatorsAsync() {
            this.ListLocatorsAsync(null);
        }
        
        /// <remarks/>
        public void ListLocatorsAsync(object userState) {
            if ((this.ListLocatorsOperationCompleted == null)) {
                this.ListLocatorsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListLocatorsOperationCompleted);
            }
            this.InvokeAsync("ListLocators", new object[0], this.ListLocatorsOperationCompleted, userState);
        }
        
        private void OnListLocatorsOperationCompleted(object arg) {
            if ((this.ListLocatorsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListLocatorsCompleted(this, new ListLocatorsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esriuk.com/locatorhub")]
    public partial class RectifyResult {
        
        private RectifyResultCodes typeOfResultField;
        
        private double rectifyRecordScoreField;
        
        private LocatorMatchedRecord matchedRecordField;
        
        private string customMessageField;
        
        private int returnedCoordinateSystemField;
        
        private CoordinateProjectionStatus coordinateSystemStatusField;
        
        /// <remarks/>
        public RectifyResultCodes TypeOfResult {
            get {
                return this.typeOfResultField;
            }
            set {
                this.typeOfResultField = value;
            }
        }
        
        /// <remarks/>
        public double RectifyRecordScore {
            get {
                return this.rectifyRecordScoreField;
            }
            set {
                this.rectifyRecordScoreField = value;
            }
        }
        
        /// <remarks/>
        public LocatorMatchedRecord MatchedRecord {
            get {
                return this.matchedRecordField;
            }
            set {
                this.matchedRecordField = value;
            }
        }
        
        /// <remarks/>
        public string CustomMessage {
            get {
                return this.customMessageField;
            }
            set {
                this.customMessageField = value;
            }
        }
        
        /// <remarks/>
        public int ReturnedCoordinateSystem {
            get {
                return this.returnedCoordinateSystemField;
            }
            set {
                this.returnedCoordinateSystemField = value;
            }
        }
        
        /// <remarks/>
        public CoordinateProjectionStatus CoordinateSystemStatus {
            get {
                return this.coordinateSystemStatusField;
            }
            set {
                this.coordinateSystemStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esriuk.com/locatorhub")]
    public enum RectifyResultCodes {
        
        /// <remarks/>
        NoMatchTooVague,
        
        /// <remarks/>
        NoMatchNoResult,
        
        /// <remarks/>
        CustomMessage,
        
        /// <remarks/>
        SingleMatch,
        
        /// <remarks/>
        UnrecognisedTarget,
        
        /// <remarks/>
        LocatorDoesNotExist,
        
        /// <remarks/>
        OperationCancelled,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esriuk.com/locatorhub")]
    public partial class LocatorMatchedRecord {
        
        private LocatorColumn[] cField;
        
        private LocatorRow rField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("C")]
        public LocatorColumn[] C {
            get {
                return this.cField;
            }
            set {
                this.cField = value;
            }
        }
        
        /// <remarks/>
        public LocatorRow R {
            get {
                return this.rField;
            }
            set {
                this.rField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esriuk.com/locatorhub")]
    public partial class LocatorColumn {
        
        private string nField;
        
        private ColumnTypeCodes tField;
        
        private bool tFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string n {
            get {
                return this.nField;
            }
            set {
                this.nField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ColumnTypeCodes t {
            get {
                return this.tField;
            }
            set {
                this.tField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tSpecified {
            get {
                return this.tFieldSpecified;
            }
            set {
                this.tFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esriuk.com/locatorhub")]
    public enum ColumnTypeCodes {
        
        /// <remarks/>
        Integer,
        
        /// <remarks/>
        Long,
        
        /// <remarks/>
        String,
        
        /// <remarks/>
        ByteArray,
        
        /// <remarks/>
        DateTime,
        
        /// <remarks/>
        Decimal,
        
        /// <remarks/>
        Byte,
        
        /// <remarks/>
        Double,
        
        /// <remarks/>
        Single,
        
        /// <remarks/>
        Short,
        
        /// <remarks/>
        Char,
        
        /// <remarks/>
        Point,
        
        /// <remarks/>
        Envelope,
        
        /// <remarks/>
        Unknown,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esriuk.com/locatorhub")]
    public partial class RemoteLocator {
        
        private string locatorNameField;
        
        private string locatorDescriptionField;
        
        private string locatorIdField;
        
        /// <remarks/>
        public string LocatorName {
            get {
                return this.locatorNameField;
            }
            set {
                this.locatorNameField = value;
            }
        }
        
        /// <remarks/>
        public string LocatorDescription {
            get {
                return this.locatorDescriptionField;
            }
            set {
                this.locatorDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string LocatorId {
            get {
                return this.locatorIdField;
            }
            set {
                this.locatorIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esriuk.com/locatorhub")]
    public partial class TargetElementDefinition {
        
        private string targetElementIdentityField;
        
        private string targetElementNameField;
        
        private string targetElementDescriptionField;
        
        /// <remarks/>
        public string TargetElementIdentity {
            get {
                return this.targetElementIdentityField;
            }
            set {
                this.targetElementIdentityField = value;
            }
        }
        
        /// <remarks/>
        public string TargetElementName {
            get {
                return this.targetElementNameField;
            }
            set {
                this.targetElementNameField = value;
            }
        }
        
        /// <remarks/>
        public string TargetElementDescription {
            get {
                return this.targetElementDescriptionField;
            }
            set {
                this.targetElementDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esriuk.com/locatorhub")]
    public partial class LocatorCapabilities {
        
        private CapabilitiesResultCodes typeOfResultField;
        
        private int coordinateSystemField;
        
        private TargetElementDefinition[] targetElementsField;
        
        /// <remarks/>
        public CapabilitiesResultCodes TypeOfResult {
            get {
                return this.typeOfResultField;
            }
            set {
                this.typeOfResultField = value;
            }
        }
        
        /// <remarks/>
        public int CoordinateSystem {
            get {
                return this.coordinateSystemField;
            }
            set {
                this.coordinateSystemField = value;
            }
        }
        
        /// <remarks/>
        public TargetElementDefinition[] TargetElements {
            get {
                return this.targetElementsField;
            }
            set {
                this.targetElementsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esriuk.com/locatorhub")]
    public enum CapabilitiesResultCodes {
        
        /// <remarks/>
        LocatorDoesNotExist,
        
        /// <remarks/>
        OperationCancelled,
        
        /// <remarks/>
        CapabilitiesListed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esriuk.com/locatorhub")]
    public partial class ReverseGeocodeResult {
        
        private ReverseGeocodeResultCodes typeOfResultField;
        
        private string customMessageField;
        
        private ReverseGeocodeLimit limitField;
        
        private string limitReasonField;
        
        private LocatorTable tableDataField;
        
        private CoordinateProjectionStatus coordinateSystemStatusField;
        
        private int returnedCoordinateSystemField;
        
        private int duplicateLocationsMaximumEnclosingCountField;
        
        /// <remarks/>
        public ReverseGeocodeResultCodes TypeOfResult {
            get {
                return this.typeOfResultField;
            }
            set {
                this.typeOfResultField = value;
            }
        }
        
        /// <remarks/>
        public string CustomMessage {
            get {
                return this.customMessageField;
            }
            set {
                this.customMessageField = value;
            }
        }
        
        /// <remarks/>
        public ReverseGeocodeLimit Limit {
            get {
                return this.limitField;
            }
            set {
                this.limitField = value;
            }
        }
        
        /// <remarks/>
        public string LimitReason {
            get {
                return this.limitReasonField;
            }
            set {
                this.limitReasonField = value;
            }
        }
        
        /// <remarks/>
        public LocatorTable TableData {
            get {
                return this.tableDataField;
            }
            set {
                this.tableDataField = value;
            }
        }
        
        /// <remarks/>
        public CoordinateProjectionStatus CoordinateSystemStatus {
            get {
                return this.coordinateSystemStatusField;
            }
            set {
                this.coordinateSystemStatusField = value;
            }
        }
        
        /// <remarks/>
        public int ReturnedCoordinateSystem {
            get {
                return this.returnedCoordinateSystemField;
            }
            set {
                this.returnedCoordinateSystemField = value;
            }
        }
        
        /// <remarks/>
        public int DuplicateLocationsMaximumEnclosingCount {
            get {
                return this.duplicateLocationsMaximumEnclosingCountField;
            }
            set {
                this.duplicateLocationsMaximumEnclosingCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esriuk.com/locatorhub")]
    public enum ReverseGeocodeResultCodes {
        
        /// <remarks/>
        NoMatchNoResult,
        
        /// <remarks/>
        CustomMessage,
        
        /// <remarks/>
        UnrecognisedTarget,
        
        /// <remarks/>
        LocatorDoesNotExist,
        
        /// <remarks/>
        OperationCancelled,
        
        /// <remarks/>
        MethodNotSupported,
        
        /// <remarks/>
        InputPointCoordinateConversionFailed,
        
        /// <remarks/>
        Successful,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esriuk.com/locatorhub")]
    public enum ReverseGeocodeLimit {
        
        /// <remarks/>
        NotApplicable,
        
        /// <remarks/>
        MaximumSearchRadius,
        
        /// <remarks/>
        MaximumCount,
        
        /// <remarks/>
        LocatorMaximumSearchRadius,
        
        /// <remarks/>
        LocatorMaximumCount,
        
        /// <remarks/>
        LocatorOther,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esriuk.com/locatorhub")]
    public partial class LocatorTable {
        
        private LocatorColumn[] cField;
        
        private LocatorRow[] rField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("C")]
        public LocatorColumn[] C {
            get {
                return this.cField;
            }
            set {
                this.cField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("R")]
        public LocatorRow[] R {
            get {
                return this.rField;
            }
            set {
                this.rField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esriuk.com/locatorhub")]
    public partial class LocatorRow {
        
        private string[] vField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("V", IsNullable=true)]
        public string[] V {
            get {
                return this.vField;
            }
            set {
                this.vField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esriuk.com/locatorhub")]
    public enum CoordinateProjectionStatus {
        
        /// <remarks/>
        NotRequired,
        
        /// <remarks/>
        NotPossible,
        
        /// <remarks/>
        NoProjectionEngineSupport,
        
        /// <remarks/>
        Transformed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esriuk.com/locatorhub")]
    public partial class FetchRecordResult {
        
        private FetchRecordResultCodes typeOfResultField;
        
        private LocatorTable tableDataField;
        
        private CoordinateProjectionStatus coordinateSystemStatusField;
        
        private int returnedCoordinateSystemField;
        
        /// <remarks/>
        public FetchRecordResultCodes TypeOfResult {
            get {
                return this.typeOfResultField;
            }
            set {
                this.typeOfResultField = value;
            }
        }
        
        /// <remarks/>
        public LocatorTable TableData {
            get {
                return this.tableDataField;
            }
            set {
                this.tableDataField = value;
            }
        }
        
        /// <remarks/>
        public CoordinateProjectionStatus CoordinateSystemStatus {
            get {
                return this.coordinateSystemStatusField;
            }
            set {
                this.coordinateSystemStatusField = value;
            }
        }
        
        /// <remarks/>
        public int ReturnedCoordinateSystem {
            get {
                return this.returnedCoordinateSystemField;
            }
            set {
                this.returnedCoordinateSystemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esriuk.com/locatorhub")]
    public enum FetchRecordResultCodes {
        
        /// <remarks/>
        NoMatchNoResult,
        
        /// <remarks/>
        SingleRecord,
        
        /// <remarks/>
        ManyRecords,
        
        /// <remarks/>
        UnrecognisedTarget,
        
        /// <remarks/>
        LocatorDoesNotExist,
        
        /// <remarks/>
        OperationCancelled,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esriuk.com/locatorhub")]
    public partial class PickItem {
        
        private double scoreField;
        
        private string descriptionField;
        
        private int recordIdField;
        
        private bool hasChildrenField;
        
        /// <remarks/>
        public double Score {
            get {
                return this.scoreField;
            }
            set {
                this.scoreField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public int RecordId {
            get {
                return this.recordIdField;
            }
            set {
                this.recordIdField = value;
            }
        }
        
        /// <remarks/>
        public bool HasChildren {
            get {
                return this.hasChildrenField;
            }
            set {
                this.hasChildrenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esriuk.com/locatorhub")]
    public partial class MatchResult {
        
        private MatchResultCodes typeOfResultField;
        
        private PickItem[] pickListItemsField;
        
        private double matchedRecordScoreField;
        
        private LocatorMatchedRecord matchedRecordField;
        
        private string customMessageField;
        
        private int returnedCoordinateSystemField;
        
        private CoordinateProjectionStatus coordinateSystemStatusField;
        
        private string cacheIdentifierField;
        
        /// <remarks/>
        public MatchResultCodes TypeOfResult {
            get {
                return this.typeOfResultField;
            }
            set {
                this.typeOfResultField = value;
            }
        }
        
        /// <remarks/>
        public PickItem[] PickListItems {
            get {
                return this.pickListItemsField;
            }
            set {
                this.pickListItemsField = value;
            }
        }
        
        /// <remarks/>
        public double MatchedRecordScore {
            get {
                return this.matchedRecordScoreField;
            }
            set {
                this.matchedRecordScoreField = value;
            }
        }
        
        /// <remarks/>
        public LocatorMatchedRecord MatchedRecord {
            get {
                return this.matchedRecordField;
            }
            set {
                this.matchedRecordField = value;
            }
        }
        
        /// <remarks/>
        public string CustomMessage {
            get {
                return this.customMessageField;
            }
            set {
                this.customMessageField = value;
            }
        }
        
        /// <remarks/>
        public int ReturnedCoordinateSystem {
            get {
                return this.returnedCoordinateSystemField;
            }
            set {
                this.returnedCoordinateSystemField = value;
            }
        }
        
        /// <remarks/>
        public CoordinateProjectionStatus CoordinateSystemStatus {
            get {
                return this.coordinateSystemStatusField;
            }
            set {
                this.coordinateSystemStatusField = value;
            }
        }
        
        /// <remarks/>
        public string CacheIdentifier {
            get {
                return this.cacheIdentifierField;
            }
            set {
                this.cacheIdentifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esriuk.com/locatorhub")]
    public enum MatchResultCodes {
        
        /// <remarks/>
        PickList,
        
        /// <remarks/>
        NoMatchTooVague,
        
        /// <remarks/>
        NoMatchNoResult,
        
        /// <remarks/>
        CustomMessage,
        
        /// <remarks/>
        SingleMatch,
        
        /// <remarks/>
        CachedQueryResultsTimedOut,
        
        /// <remarks/>
        UnrecognisedTarget,
        
        /// <remarks/>
        LocatorDoesNotExist,
        
        /// <remarks/>
        OperationCancelled,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esriuk.com/locatorhub")]
    public partial class Point {
        
        private double xField;
        
        private double yField;
        
        private System.Nullable<double> zField;
        
        /// <remarks/>
        public double X {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        public double Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Z {
            get {
                return this.zField;
            }
            set {
                this.zField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esriuk.com/locatorhub")]
    public partial class GeocodeResult {
        
        private GeoCodeResultCodes typeOfResultField;
        
        private Point geocodedLocationField;
        
        private double geocodedRecordScoreField;
        
        private int returnedCoordinateSystemField;
        
        private CoordinateProjectionStatus coordinateSystemStatusField;
        
        private string customMessageField;
        
        /// <remarks/>
        public GeoCodeResultCodes TypeOfResult {
            get {
                return this.typeOfResultField;
            }
            set {
                this.typeOfResultField = value;
            }
        }
        
        /// <remarks/>
        public Point GeocodedLocation {
            get {
                return this.geocodedLocationField;
            }
            set {
                this.geocodedLocationField = value;
            }
        }
        
        /// <remarks/>
        public double GeocodedRecordScore {
            get {
                return this.geocodedRecordScoreField;
            }
            set {
                this.geocodedRecordScoreField = value;
            }
        }
        
        /// <remarks/>
        public int ReturnedCoordinateSystem {
            get {
                return this.returnedCoordinateSystemField;
            }
            set {
                this.returnedCoordinateSystemField = value;
            }
        }
        
        /// <remarks/>
        public CoordinateProjectionStatus CoordinateSystemStatus {
            get {
                return this.coordinateSystemStatusField;
            }
            set {
                this.coordinateSystemStatusField = value;
            }
        }
        
        /// <remarks/>
        public string CustomMessage {
            get {
                return this.customMessageField;
            }
            set {
                this.customMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esriuk.com/locatorhub")]
    public enum GeoCodeResultCodes {
        
        /// <remarks/>
        NoMatchTooVague,
        
        /// <remarks/>
        NoMatchNoResult,
        
        /// <remarks/>
        CustomMessage,
        
        /// <remarks/>
        UnrecognisedTarget,
        
        /// <remarks/>
        LocatorDoesNotExist,
        
        /// <remarks/>
        OperationCancelled,
        
        /// <remarks/>
        GeocodeSuccessful,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esriuk.com/locatorhub")]
    public enum RecordIdentifierType {
        
        /// <remarks/>
        LocatorFamilyId,
        
        /// <remarks/>
        LocatorId,
        
        /// <remarks/>
        DatasetFamilyId,
        
        /// <remarks/>
        DatasetId,
        
        /// <remarks/>
        Custom,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esriuk.com/locatorhub")]
    public enum DistanceUnits {
        
        /// <remarks/>
        Unknown,
        
        /// <remarks/>
        Inches,
        
        /// <remarks/>
        Points,
        
        /// <remarks/>
        Feet,
        
        /// <remarks/>
        Yards,
        
        /// <remarks/>
        Miles,
        
        /// <remarks/>
        NauticalMiles,
        
        /// <remarks/>
        Millimeters,
        
        /// <remarks/>
        Centimeters,
        
        /// <remarks/>
        Meters,
        
        /// <remarks/>
        Kilometers,
        
        /// <remarks/>
        DecimalDegrees,
        
        /// <remarks/>
        Decimeters,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void RectifyCompletedEventHandler(object sender, RectifyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RectifyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RectifyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RectifyResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RectifyResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void Rectify_BinaryCompletedEventHandler(object sender, Rectify_BinaryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Rectify_BinaryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Rectify_BinaryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GeocodeCompletedEventHandler(object sender, GeocodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GeocodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GeocodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GeocodeResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GeocodeResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void Geocode_BinaryCompletedEventHandler(object sender, Geocode_BinaryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Geocode_BinaryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Geocode_BinaryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void MatchCompletedEventHandler(object sender, MatchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MatchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MatchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MatchResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MatchResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void Match_BinaryCompletedEventHandler(object sender, Match_BinaryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Match_BinaryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Match_BinaryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void FetchRecordCompletedEventHandler(object sender, FetchRecordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FetchRecordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FetchRecordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FetchRecordResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FetchRecordResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void FetchRecord_BinaryCompletedEventHandler(object sender, FetchRecord_BinaryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FetchRecord_BinaryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FetchRecord_BinaryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ReverseGeocodeCompletedEventHandler(object sender, ReverseGeocodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReverseGeocodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReverseGeocodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReverseGeocodeResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReverseGeocodeResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ReverseGeocode_BinaryCompletedEventHandler(object sender, ReverseGeocode_BinaryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReverseGeocode_BinaryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReverseGeocode_BinaryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CapabilitiesCompletedEventHandler(object sender, CapabilitiesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CapabilitiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CapabilitiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LocatorCapabilities Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LocatorCapabilities)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ListLocatorsCompletedEventHandler(object sender, ListLocatorsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListLocatorsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListLocatorsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RemoteLocator[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RemoteLocator[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591